syntax = "proto3";

package ET;

message ProtoAddress
{
	int32 Process = 1;
	int32 Fiber = 2;
}

message ProtoActorId
{
	ProtoAddress Address = 1;
	int64 InstanceId = 2;
}


// res ObjectQueryResponse
message ObjectQueryRequest // req
{
	int32 RpcId = 1;
	int64 Key = 2;
	int64 InstanceId = 3;
}

message ObjectQueryResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	bytes Entity = 4;
}

// res A2M_Reload
message M2A_Reload // req
{
	int32 RpcId = 1;
}

message A2M_Reload // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res G2G_LockResponse
message G2G_LockRequest // req
{
	int32 RpcId = 1;
	int64 Id = 2;
	string Address = 3;
}

message G2G_LockResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res G2G_LockReleaseResponse
message G2G_LockReleaseRequest // req
{
	int32 RpcId = 1;
	int64 Id = 2;
	string Address = 3;
}

message G2G_LockReleaseResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res ObjectAddResponse
message ObjectAddRequest // req
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
	ProtoActorId ActorId = 4;
}

message ObjectAddResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res ObjectLockResponse
message ObjectLockRequest // req
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
	ProtoActorId ActorId = 4;
	int32 Time = 5;
}
message ObjectLockResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res ObjectUnLockResponse
message ObjectUnLockRequest // req
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
	ProtoActorId OldActorId = 4;
	ProtoActorId NewActorId = 5;
}
message ObjectUnLockResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res ObjectRemoveResponse
message ObjectRemoveRequest // req
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
}
message ObjectRemoveResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res ObjectGetResponse
message ObjectGetRequest // req
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
}
message ObjectGetResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int32 Type = 4;
	ProtoActorId ActorId = 5;
}

// res G2R_GetLoginKey
message R2G_GetLoginKey // req
{
	int32 RpcId = 1;
	string Account = 2;
}

message G2R_GetLoginKey // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Key = 4;
	int64 GateId = 5;
}

message G2M_SessionDisconnect // req
{
	int32 RpcId = 1;
}

// res M2M_UnitTransferResponse
message M2M_UnitTransferRequest // req
{
	int32 RpcId = 1;
	ProtoActorId OldActorId = 2;
	bytes Unit = 3;
	repeated bytes Entitys = 4;
}

message M2M_UnitTransferResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}