syntax = "proto3";
package ET;

message float3
{
	float x = 1;
	float y = 2;
	float z = 3;
}

message quaternion
{
	float x = 1;
	float y = 2;
	float z = 3;
	float w = 4;
}


message RouterSync
{
	uint32 ConnectId = 1;
	string Address = 2;
}

// res M2C_TestResponse
message C2M_TestRequest // req
{
	int32 RpcId = 1;
	string request = 2;
}

message M2C_TestResponse // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string response = 4;
}

// res G2C_EnterMap
message C2G_EnterMap // req
{
	int32 RpcId = 1;
}

message G2C_EnterMap // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	/// 自己的UnitId
	int64 MyId = 4;
}

message MoveInfo
{
	repeated float3 Points = 1;
	quaternion Rotation = 2;
	int32 TurnSpeed = 3;
}

message UnitInfo
{
	int64 UnitId = 1;
	int32 ConfigId = 2;
	int32 Type = 3;
	float3 Position = 4;
	float3 Forward = 5;
	map<int32, int64> KV = 6;
	MoveInfo MoveInfo = 7;
}

message M2C_CreateUnits // msg
{
	repeated UnitInfo Units = 1;
}

message M2C_CreateMyUnit // msg
{
	UnitInfo Unit = 1;
}

message M2C_StartSceneChange // msg
{
	int64 SceneInstanceId = 1;
	string SceneName = 2;
}

message M2C_RemoveUnits // msg
{
	repeated int64 Units = 1;
}

message C2M_PathfindingResult // msg
{
	int32 RpcId = 1;
	float3 Position = 2;
}

message C2M_Stop // msg
{
	int32 RpcId = 1;
}

message M2C_PathfindingResult // msg
{
	int64 Id = 1;
	float3 Position = 2;
	repeated float3 Points = 3;
}

message M2C_Stop // msg
{
	int32 Error = 1;
	int64 Id = 2;
	float3 Position = 3;
	quaternion Rotation = 4;
}

// res G2C_Ping
message C2G_Ping // req
{
	int32 RpcId = 1;
}

message G2C_Ping // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}


message G2C_Test // msg
{
}

// res M2C_Reload
message C2M_Reload // req
{
	int32 RpcId = 1;
	string Account = 2;
	string Password = 3;
}

message M2C_Reload // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res R2C_Login
message C2R_Login // req
{
	int32 RpcId = 1;
	string  Account = 2;  // 帐号
	string  Password = 3;  // 密码
}

message R2C_Login // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string Address = 4;
	int64 Key = 5;
	int64 GateId = 6;
}

// res G2C_LoginGate
message C2G_LoginGate // req
{
	int32 RpcId = 1;
	int64 Key = 2;  // 帐号
	int64 GateId = 3;
}

message G2C_LoginGate // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}

message G2C_TestHotfixMessage // msg
{
	string Info = 1;
}

// res M2C_TestRobotCase
message C2M_TestRobotCase // req
{
	int32 RpcId = 1;
	int32 N = 2;
}

message M2C_TestRobotCase // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int32 N = 4;
}

message C2M_TestRobotCase2 // msg
{
	int32 RpcId = 1;
	int32 N = 2;
}

message M2C_TestRobotCase2 // msg
{
	int32 RpcId = 1;
	int32 N = 2;
}

// res M2C_TransferMap
message C2M_TransferMap // req
{
	int32 RpcId = 1;
}

message M2C_TransferMap // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// res G2C_Benchmark
message C2G_Benchmark // req
{
	int32 RpcId = 1;
}

message G2C_Benchmark // res
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}